return function(c, dark)
  return {
    ["@attribute"] = { fg = c.yellow },
    ["@attribute.builtin"] = { fg = c.cyan },
    ["@boolean"] = { fg = c.blue },
    ["@character"] = { fg = c.orange },
    ["@character.special"] = { fg = c.foreground },
    ["@comment"] = { fg = c.green, italic = true },
    ["@comment.error"] = { fg = c.red, bold = true },
    ["@comment.note"] = { fg = c.cyan, bold = true },
    ["@comment.todo"] = { fg = c.accent, bg = c.background, bold = true },
    ["@comment.warning"] = { fg = c.accent, bold = true },
    ["@constant"] = { fg = c.bright_blue },
    ["@constant.builtin"] = { fg = c.blue },
    ["@constant.macro"] = { fg = c.cyan },
    ["@constructor"] = { fg = c.blue },
    ["@constructor.python"] = { fg = c.cyan },
    ["@diff.delta"] = dark and { bg = "#4b1818" } or { bg = "#ffcccc" },
    ["@diff.minus"] = dark and { bg = "#6f1313" } or { bg = "#ffa3a3" },
    ["@diff.plus"] = dark and { bg = "#4b5632" } or { bg = "#ebf1dd" },
    ["@function"] = { fg = c.yellow },
    ["@function.builtin"] = { fg = c.yellow },
    ["@function.macro"] = { fg = c.yellow },
    ["@function.method"] = { fg = c.yellow },
    ["@keyword"] = { fg = c.blue },
    ["@keyword.conditional"] = { fg = c.bright_magenta },
    ["@keyword.exception"] = { fg = c.bright_magenta },
    ["@keyword.import"] = { fg = c.bright_magenta },
    ["@keyword.repeat"] = { fg = c.bright_magenta },
    ["@keyword.return"] = { fg = c.bright_magenta },
    ["@label"] = { fg = c.bright_blue },
    ["@lsp.mod.deprecated"] = dark and { sp = "#ffc0b9", strikethrough = true } or { sp = "#590008", strikethrough = true },
    ["@lsp.type.class"] = { fg = c.cyan },
    ["@lsp.type.comment"] = { fg = c.green, italic = true },
    ["@lsp.type.comment.c"] = dark and { fg = "#51504f" } or { fg = "#b2dfdb" },
    ["@lsp.type.comment.cpp"] = dark and { fg = "#51504f" } or { fg = "#b2dfdb" },
    ["@lsp.type.decorator"] = { fg = c.yellow },
    ["@lsp.type.enum"] = { fg = c.cyan },
    ["@lsp.type.enumMember"] = { fg = c.bright_blue },
    ["@lsp.type.event"] = { fg = c.cyan },
    ["@lsp.type.function"] = { fg = c.yellow },
    ["@lsp.type.interface"] = { fg = c.cyan },
    ["@lsp.type.keyword"] = { fg = c.blue },
    ["@lsp.type.macro"] = { fg = c.bright_blue },
    ["@lsp.type.member"] = { fg = c.yellow },
    ["@lsp.type.method"] = { fg = c.yellow },
    ["@lsp.type.modifier"] = { fg = c.blue },
    ["@lsp.type.namespace"] = { fg = c.cyan },
    ["@lsp.type.number"] = { fg = c.bright_green },
    ["@lsp.type.parameter"] = { fg = c.bright_blue },
    ["@lsp.type.property"] = { fg = c.bright_blue },
    ["@lsp.type.regexp"] = { fg = c.orange },
    ["@lsp.type.string"] = { fg = c.orange },
    ["@lsp.type.struct"] = { fg = c.cyan },
    ["@lsp.type.type"] = { fg = c.cyan },
    ["@lsp.type.typeParameter"] = { fg = c.cyan },
    ["@lsp.type.variable"] = { fg = c.bright_blue },
    ["@lsp.typemod.keyword.controlFlow"] = { fg = c.bright_magenta },
    ["@lsp.typemod.property.readonly"] = { fg = c.bright_blue },
    ["@lsp.typemod.type.defaultLibrary"] = { fg = c.blue },
    ["@lsp.typemod.variable.constant"] = { fg = c.bright_blue },
    ["@lsp.typemod.variable.readonly"] = { fg = c.bright_blue },
    ["@markup"] = { fg = c.accent },
    ["@markup.heading"] = dark and { fg = c.blue, bold = true } or { fg = c.accent, bold = true },
    ["@markup.heading.1"] = dark and { fg = c.blue, bold = true } or { fg = c.accent, bold = true },
    ["@markup.heading.1.markdown"] = { fg = c.blue, bold = true },
    ["@markup.heading.2"] = dark and { fg = c.blue, bold = true } or { fg = c.accent, bold = true },
    ["@markup.heading.2.markdown"] = { fg = c.orange, bold = true },
    ["@markup.heading.3"] = dark and { fg = c.blue, bold = true } or { fg = c.accent, bold = true },
    ["@markup.heading.3.markdown"] = { fg = c.yellow, bold = true },
    ["@markup.heading.4"] = dark and { fg = c.blue, bold = true } or { fg = c.accent, bold = true },
    ["@markup.heading.4.markdown"] = { fg = c.green, bold = true },
    ["@markup.heading.4.vimdoc"] = dark and { fg = c.blue, bold = true } or { fg = c.accent, bold = true },
    ["@markup.heading.5"] = dark and { fg = c.blue, bold = true } or { fg = c.accent, bold = true },
    ["@markup.heading.5.markdown"] = { fg = c.blue, bold = true },
    ["@markup.heading.6"] = dark and { fg = c.blue, bold = true } or { fg = c.accent, bold = true },
    ["@markup.heading.6.markdown"] = { fg = c.bright_magenta, bold = true },
    ["@markup.italic"] = { fg = c.foreground, italic = true },
    ["@markup.link.label"] = { fg = c.bright_blue },
    ["@markup.link.url"] = { fg = c.foreground },
    ["@markup.list.checked"] = { fg = c.accent, bg = c.background, bold = true },
    ["@markup.list.unchecked"] = { fg = c.accent, bg = c.background, bold = true },
    ["@markup.raw"] = { fg = c.foreground },
    ["@markup.raw.markdown"] = { fg = c.orange },
    ["@markup.raw.markdown_inline"] = { fg = c.orange },
    ["@markup.strikethrough"] = { fg = c.foreground, strikethrough = true },
    ["@markup.strong"] = dark and { fg = c.blue, bold = true } or { fg = c.magenta, bold = true },
    ["@markup.underline"] = { fg = c.accent, underline = true },
    ["@module"] = { fg = c.cyan },
    ["@module.builtin"] = { fg = c.accent },
    ["@number"] = { fg = c.bright_green },
    ["@number.float"] = { fg = c.bright_green },
    ["@property"] = { fg = c.bright_blue },
    ["@punctuation"] = { fg = c.foreground },
    ["@punctuation.bracket"] = { fg = c.foreground },
    ["@punctuation.delimiter"] = { fg = c.foreground },
    ["@punctuation.special"] = { fg = c.foreground },
    ["@string"] = { fg = c.orange },
    ["@string.escape"] = { fg = c.foreground },
    ["@string.regexp"] = { fg = c.orange },
    ["@string.special"] = { fg = c.foreground },
    ["@string.special.vimdoc"] = { fg = c.foreground },
    ["@tag"] = { fg = c.blue },
    ["@tag.attribute"] = { fg = c.bright_blue },
    ["@tag.builtin"] = { fg = c.blue },
    ["@tag.delimiter"] = { fg = c.muted },
    ["@type"] = { fg = c.cyan },
    ["@type.builtin"] = { fg = c.blue },
    ["@type.builtin.tsx"] = { fg = c.cyan },
    ["@type.builtin.typescript"] = { fg = c.cyan },
    ["@variable"] = { fg = c.bright_blue },
    ["@variable.builtin"] = { fg = c.blue },
    ["@variable.member"] = { fg = c.bright_blue },
    ["@variable.parameter"] = { fg = c.bright_blue },
    ["@variable.parameter.builtin"] = { fg = c.accent },
    ["@variable.parameter.vimdoc"] = { fg = c.bright_blue },
    Added = dark and { fg = "#b3f6c0" } or { fg = "#005523" },
    Boolean = { fg = c.blue },
    Changed = dark and { fg = "#8cf8f7" } or { fg = "#007373" },
    Character = { fg = c.orange },
    ColorColumn = dark and { bg = "#222222" } or { bg = "#e5e5e5" },
    Comment = { fg = c.green, italic = true },
    Conceal = { fg = c.foreground, bg = c.background },
    Conditional = { fg = c.bright_magenta },
    Constant = { fg = c.blue },
    CurSearch = dark and { fg = "#07080d", bg = "#fce094" } or { fg = "#eef1f8", bg = "#6b5300" },
    Cursor = dark and { fg = c.bright_foreground, bg = "#aeafad" } or { fg = c.bright_foreground, bg = "#767676" },
    CursorColumn = dark and { bg = "#222222" } or { bg = "#e5e5e5" },
    CursorLine = dark and { bg = "#222222" } or { bg = "#e5e5e5" },
    CursorLineFold = { fg = c.muted, bg = c.background },
    CursorLineNr = { fg = c.foreground, bg = c.background },
    CursorLineSign = { bg = c.background },
    Debug = { fg = c.foreground },
    Define = { fg = c.bright_magenta },
    Delimiter = { fg = c.foreground },
    DiagnosticFloatingError = { fg = c.red },
    DiagnosticFloatingHint = { fg = c.blue },
    DiagnosticFloatingInfo = { fg = c.blue },
    DiagnosticFloatingOk = { fg = c.cyan },
    DiagnosticFloatingWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticOk = { fg = c.cyan },
    DiagnosticSignError = { fg = c.red },
    DiagnosticSignHint = { fg = c.blue },
    DiagnosticSignInfo = { fg = c.blue },
    DiagnosticSignOk = { fg = c.cyan },
    DiagnosticSignWarn = { fg = c.yellow },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineOk = dark and { sp = "#b3f6c0", underline = true } or { sp = "#005523", underline = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
    DiagnosticUnnecessary = { fg = "#729db3" },
    DiagnosticVirtualLinesInfo = { fg = c.blue },
    DiagnosticVirtualLinesOk = { fg = c.cyan },
    DiagnosticVirtualLinesWarn = { fg = c.yellow },
    DiagnosticVirtualTextInfo = { fg = c.blue },
    DiagnosticVirtualTextOk = { fg = c.cyan },
    DiagnosticVirtualTextWarn = { fg = c.yellow },
    DiagnosticWarn = { fg = c.yellow },
    DiffAdd = dark and { bg = "#4b5632" } or { bg = "#ebf1dd" },
    DiffChange = dark and { bg = "#4b1818" } or { bg = "#ffcccc" },
    DiffDelete = dark and { bg = "#6f1313" } or { bg = "#ffa3a3" },
    DiffText = dark and { bg = "#6f1313" } or { bg = "#ffa3a3" },
    DiffTextAdd = dark and { bg = "#6f1313" } or { bg = "#ffa3a3" },
    Directory = { fg = c.blue, bg = c.background },
    EndOfBuffer = { fg = c.background },
    Error = { fg = c.red, bg = c.background, sp = c.red, undercurl = true },
    ErrorMsg = { fg = c.red, bg = c.background },
    Exception = { fg = c.bright_magenta },
    Float = { fg = c.bright_green },
    FloatBorder = { bg = c.dark_background },
    FloatFooter = { bold = true },
    FloatTitle = { bold = true },
    FoldColumn = { fg = c.muted, bg = c.background },
    Folded = dark and { bg = "#202d39" } or { bg = "#e6f3ff" },
    Function = { fg = c.yellow },
    GitSignsAdd = { fg = c.green },
    GitSignsAddLn = { fg = c.background, bg = c.green },
    GitSignsChange = { fg = c.blue },
    GitSignsChangeLn = { fg = c.background, bg = c.yellow },
    GitSignsDelete = { fg = c.red },
    GitSignsDeleteLn = { fg = c.background, bg = c.red },
    IblIndent = dark and { fg = "#404040" } or { fg = "#d2d2d2" },
    IblScope = dark and { fg = "#707070" } or { fg = "#929292" },
    IblWhitespace = dark and { fg = "#404040" } or { fg = "#d2d2d2" },
    Identifier = { fg = c.bright_blue },
    IncSearch = dark and { bg = "#515c6a" } or { bg = "#a8ac94" },
    Include = { fg = c.bright_magenta },
    Keyword = { fg = c.bright_magenta },
    Label = { fg = c.bright_magenta },
    LineNr = { fg = c.muted, bg = c.background },
    LineNrAbove = { fg = c.muted, bg = c.background },
    LineNrBelow = { fg = c.muted, bg = c.background },
    LspCodeLens = dark and { fg = c.muted } or { fg = c.dark_background },
    LspCodeLensSeparator = dark and { fg = c.muted } or { fg = c.dark_background },
    LspFloatWinBorder = dark and { fg = c.muted } or { fg = c.dark_background },
    LspFloatWinNormal = { fg = c.foreground },
    LspInlayHint = dark and { fg = "#6a6a6a" } or { fg = "#868686" },
    LspReferenceRead = dark and { bg = "#343b41" } or { bg = "#d7eafe" },
    LspReferenceTarget = dark and { bg = "#343b41" } or { bg = "#d7eafe" },
    LspReferenceText = dark and { bg = "#343b41" } or { bg = "#d7eafe" },
    LspReferenceWrite = dark and { bg = "#343b41" } or { bg = "#d7eafe" },
    LspSignatureActiveParameter = { bg = c.selection },
    Macro = { fg = c.bright_magenta },
    MatchParen = dark and { bg = "#51504f" } or { bg = "#b2dfdb" },
    MiniIconsBlue = { fg = "#18a2fe" },
    MiniIconsGrey = { fg = c.foreground },
    MiniIconsOrange = { fg = c.red },
    MiniIconsPurple = { fg = c.bright_magenta },
    MiniIconsYellow = { fg = c.brown },
    MiniSurround = dark and { bg = "#515c6a" } or { bg = "#a8ac94" },
    ModeMsg = { fg = c.foreground, bg = c.dark_background },
    MoreMsg = { fg = c.foreground, bg = c.dark_background },
    NonText = dark and { fg = c.muted } or { fg = c.dark_background },
    NormalFloat = { bg = c.dark_background },
    Number = { fg = c.bright_green },
    OilChange = { fg = c.accent },
    OilCreate = { fg = c.blue },
    OilDirHidden = { fg = c.green, italic = true },
    OilEmpty = { fg = c.green, italic = true },
    OilFileHidden = { fg = c.green, italic = true },
    OilHidden = { fg = c.green, italic = true },
    OilLinkHidden = { fg = c.green, italic = true },
    OilLinkTarget = { fg = c.green, italic = true },
    OilLinkTargetHidden = { fg = c.green, italic = true },
    OilMove = { fg = c.yellow },
    OilOrphanLinkHidden = { fg = c.green, italic = true },
    OilRestore = { fg = c.blue },
    OilSocket = { fg = c.bright_magenta },
    OilSocketHidden = { fg = c.green, italic = true },
    OilTrashSourcePath = { fg = c.green, italic = true },
    Pmenu = dark and { fg = c.foreground, bg = c.dark_background } or { bg = c.dark_background },
    PmenuBorder = dark and { fg = c.foreground, bg = c.dark_background } or { bg = c.dark_background },
    PmenuExtra = dark and { fg = c.foreground, bg = c.dark_background } or { bg = c.dark_background },
    PmenuExtraSel = dark and { fg = c.foreground, bg = "#04395e" } or { bg = c.darker_background },
    PmenuKind = dark and { fg = c.foreground, bg = c.dark_background } or { bg = c.dark_background },
    PmenuKindSel = dark and { fg = c.foreground, bg = "#04395e" } or { bg = c.darker_background },
    PmenuMatch = { bold = true },
    PmenuMatchSel = { bold = true },
    PmenuSbar = dark and { bg = "#343b41" } or { bg = "#767676" },
    PmenuSel = dark and { fg = c.foreground, bg = "#04395e" } or { bg = c.darker_background },
    PmenuThumb = { bg = c.foreground },
    PreCondit = { fg = c.bright_magenta },
    PreProc = { fg = c.bright_magenta },
    Question = { fg = c.blue, bg = c.background },
    QuickFixLine = { bold = true },
    Removed = dark and { fg = "#ffc0b9" } or { fg = "#590008" },
    Repeat = { fg = c.bright_magenta },
    Search = dark and { bg = "#613315" } or { bg = "#f8c9ab" },
    SignColumn = { bg = c.background },
    Special = { fg = c.accent },
    SpecialChar = { fg = c.foreground },
    SpecialComment = { fg = c.green },
    SpecialKey = { fg = c.blue },
    SpellCap = { sp = c.yellow, undercurl = true },
    SpellLocal = { sp = c.blue, undercurl = true },
    Statement = { fg = c.bright_magenta },
    StatusLine = { fg = c.foreground, bg = c.lighter_background },
    StatusLineNC = { fg = c.foreground, bg = c.dark_background },
    StatusLineTerm = { fg = c.foreground, bg = c.lighter_background },
    StatusLineTermNC = { fg = c.foreground, bg = c.dark_background },
    StorageClass = { fg = c.blue },
    String = { fg = c.orange },
    Structure = { fg = c.cyan },
    Substitute = dark and { bg = "#613315" } or { bg = "#f8c9ab" },
    TabLine = { fg = c.foreground, bg = c.dark_background },
    TabLineFill = { fg = c.foreground, bg = c.darker_background },
    TabLineSel = { fg = c.foreground, bg = c.background },
    Tag = { fg = c.foreground },
    TelescopeMatching = dark and { fg = "#18a2fe", bold = true } or { fg = "#ffa500", bold = true },
    TelescopeMultiSelection = dark and { fg = c.foreground, bg = "#04395e" } or { fg = c.background, bg = "#0064c1" },
    TelescopeNormal = { fg = c.foreground },
    TelescopePreviewBorder = dark and { fg = c.muted } or { fg = c.dark_background },
    TelescopePromptBorder = dark and { fg = c.muted } or { fg = c.dark_background },
    TelescopePromptPrefix = { fg = c.foreground },
    TelescopeResultsBorder = dark and { fg = c.muted } or { fg = c.dark_background },
    TelescopeSelection = dark and { fg = c.foreground, bg = "#04395e" } or { fg = c.background, bg = "#0064c1" },
    Title = { bold = true },
    Todo = { fg = c.accent, bg = c.background, bold = true },
    Type = { fg = c.blue },
    Typedef = { fg = c.blue },
    VertSplit = { fg = c.darker_background, bg = c.background },
    VisualNOS = { bg = c.selection },
    WarningMsg = { fg = c.yellow, bg = c.background },
    Whitespace = dark and { fg = c.muted } or { fg = c.dark_background },
    WildMenu = { bg = c.selection },
    WinBar = { fg = c.foreground, bg = c.background, bold = true },
    WinBarNC = { fg = c.foreground, bg = c.background },
    WinSeparator = { fg = c.darker_background, bg = c.background },
  }
end
