[tools]
gitui = "latest"
neovim = "latest"
ripgrep = "latest"
fzf = "latest"
fd = "latest"
dust = "latest"
usage = "latest"
tmux = "latest"
node = "latest"
java = "openjdk-17"
go = "latest"
tokei = "12.1.2"
bat = "latest"
k9s = "latest"
zig = "0.14.0"
rust = "latest"
typst = "latest"
erlang = "28"
elixir = "1.19.3-otp-28"
yazi = "latest"
ruby = "3.4.6"

[tools."github:bitwarden/clients"]
version = "cli-v2025.8.0"
version_prefix = "cli-v"
asset_pattern = "bw-macos-arm64-*.zip"
bin = "bw"
