[plugins]
gitui = "https://github.com/looztra/asdf-gitui"
neovim = "https://github.com/richin13/asdf-neovim"
ripgrep = "https://gitlab.com/wt0f/asdf-ripgrep"
fzf = "https://github.com/kompiro/asdf-fzf"
fd = "https://gitlab.com/wt0f/asdf-fd"
tmux = "https://github.com/aphecetche/asdf-tmux.git"

erlang = "https://github.com/asdf-vm/asdf-erlang.git"

[tools]
gitui = "0.27.0"
neovim = "latest"
ripgrep = "latest"
fzf = "latest"
fd = "latest"
dust = "latest"
usage = "latest"
tmux = "latest"
node = "latest"
ruby = "3.4.4"
erlang = "27.2"
elixir = "1.18.1-otp-27"
java = "openjdk-17"
go = "latest"
tokei = "12.1.2"
bat = "latest"
k9s = "latest"
zig = "0.14.0"
rust = "1.83.0"
python = "3"
