[alias]
gitui = "github:gitui-org/gitui"

[tools]
gitui = "0.27.0"
neovim = "latest"
ripgrep = "latest"
fzf = "latest"
fd = "latest"
dust = "latest"
usage = "latest"
tmux = "latest"
node = "latest"
ruby = "3.4.4"
erlang = "28.0.2"
elixir = "1.18.4-otp-28"
java = "openjdk-17"
go = "latest"
tokei = "12.1.2"
bat = "latest"
k9s = "latest"
zig = "0.14.0"
rust = "1.88.0"
[tools."github:bitwarden/clients"]
version = "cli-v2025.8.0"
version_prefix = "cli-v"
asset_pattern = "bw-macos-arm64-*.zip"
bin = "bw"

[settings]
experimental = true
